maps/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('accounts/registration/', views.RegisterView.as_view(), name="registration"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('streetmarkers.urls')),
    path('user/pegs/', include('pegs.urls')),
    path('admin/', admin.site.urls),
]

pegs/urls.py
from django.urls import path

from . import views

app_name = 'pegs'

urlpatterns = [
    path('', views.PegDetailView.as_view(), name='peg_detail'),
    path('create/pegsystem/', views.PegSystemCreate.as_view(), name='pegsystem_create'),
    path('update/pegsystem/<int:pk>', views.PegSystemUpdate.as_view(), name='pegsystem_update'),
    path('delete/pegsystem/<int:pk>', views.PegSystemDelete.as_view(), name='pegsystem_delete'),
    path('<int:pk>/create/popeg/', views.POPegCreate.as_view(), name='popeg_create'),
    path('update/popeg/<int:pk>', views.POPegUpdate.as_view(), name='popeg_update'),
    path('delete/popeg/<int:pk>', views.POPegDelete.as_view(), name='popeg_delete'),
]

pegs/models.py
from django.db import models
from django.contrib.auth.models import User

class PegType(models.Model):
    typeName = models.CharField(max_length=30)
    def __str__(self):
        return self.typeName

class PegSystem(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    pegType = models.ForeignKey(PegType, on_delete=models.PROTECT, null=True)
    createdBy = models.ForeignKey(User, on_delete=models.PROTECT)
    
    @property
    def peg_count(self):
        return len(self.peg_set)

    def __str__(self):
        return self.title

class Peg(models.Model):
    content = models.CharField(max_length=30)
    notes = models.TextField(null=True, blank=True)
    pegSystem = models.ForeignKey(PegSystem, on_delete=models.CASCADE)
    pegType = models.ForeignKey(PegType, on_delete=models.PROTECT, null=True)
    def __str__(self):
        return self.content

class BasicPeg(Peg):
    encoded = models.CharField(max_length=30)

class PAOPeg(Peg): 
    person = models.CharField(max_length=30)
    action = models.CharField(max_length=30)
    object = models.CharField(max_length=30)

class POPeg(Peg): 
    person = models.CharField(max_length=30)
    object = models.CharField(max_length=30)

pegs/views.py
from django.shortcuts import get_object_or_404, render

from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import PegSystem, POPeg, PegType
from django.urls import reverse_lazy

### logging ###
import logging
import logging.config
import sys
from django.urls.base import reverse
from django.db.models import Q

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    }
}

logging.config.dictConfig(LOGGING)
######

class PegDetailView(LoginRequiredMixin, ListView):
    model = PegSystem 
    template_name = 'pegs/peg_detail.html'
    paginate_by = 5

    def get_queryset(self):
        return PegSystem.objects.filter(createdBy=self.request.user).order_by('title')


# Create views
# assert user is createdBy user

class PegSystemCreate(LoginRequiredMixin, CreateView):
    model = PegSystem 
    fields = ['title', 'description', 'pegType']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('pegs:peg_detail')

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

class POPegCreate(LoginRequiredMixin, CreateView):
    model = POPeg
    fields = ['content', 'person', 'object', 'notes']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('pegs:peg_detail')

    def form_valid(self, form):
        pegSystem = PegSystem.objects.get(pk = self.kwargs['pk'])
        form.instance.pegSystem = pegSystem
        form.instance.pegType = pegSystem.pegType
        return super().form_valid(form)


# Update views
# assert user is createdBy user

class PegSystemUpdate(LoginRequiredMixin, UpdateView):
    model = PegSystem 
    fields = ['title', 'description']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('pegs:peg_detail')

class POPegUpdate(LoginRequiredMixin, UpdateView):
    model = POPeg
    fields = ['content', 'person', 'object']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('pegs:peg_detail')

# Delete views
# assert user is createdBy user

class PegSystemDelete(LoginRequiredMixin, DeleteView):
    model = PegSystem 
    success_url = reverse_lazy('pegs:peg_detail')

class POPegDelete(LoginRequiredMixin, DeleteView):
    model = POPeg
    success_url = reverse_lazy('pegs:peg_detail')

pegs/templates/pegs/peg_detail.html
{% extends 'base_generic.html' %}

{% load static %}
{% block content %}

<content>
    {% for pegsystem in pegsystem_list %}
    <h2>
        {{ user.username|title }}'s Peg Systems
        <span class="btn btn-default btn-sm">
            <a href="{% url 'pegs:pegsystem_create' %}">
                <img src="{% static 'svg/create.svg' %}">
            </a>
        </span>
    </h2>
    <table class="table">
        <h3>
            {{ pegsystem.title }}
            <span class="btn btn-default btn-sm">
                <a href="{% url 'pegs:pegsystem_update' pegsystem.pk %}">
                    <img src="{% static 'svg/update.svg' %}">
                </a>
            </span>
            <span class="btn btn-default btn-sm">
                <a href="{% url 'pegs:pegsystem_delete' pegsystem.pk %}">
                    <img src="{% static 'svg/delete.svg' %}">
                </a>
            </span>
        </h3>
        <h6>{{ pegsystem.description }}</h6>
        <thead>
            <tr>
                <th scope="col">content</th>
                <th scope="col">person</th>
                <th scope="col">object</th>
                <td class="btn btn-default btn-sm">
                    <a href="{% url 'pegs:popeg_create' pegsystem.pk %}">
                        <img src="{% static 'svg/create.svg' %}">
                    </a>
                </td>
            </tr>
        </thead>
        <tbody>
            {% for peg in pegsystem.peg_set.all %}
            {% if peg.popeg %}
            <a href="update/popeg/{{ peg.pk }}">
                <tr>
                    <th scope="row">{{ peg.content }}</th>
                    <td>{{ peg.popeg.person }}</td>
                    <td>{{ peg.popeg.object }}</td>
                    <td class="btn btn-default btn-sm">
                        <a href="{% url 'pegs:popeg_update' peg.pk %}">
                            <img src="{% static 'svg/update.svg' %}">
                        </a>
                    </td>
                    <td class="btn btn-default btn-sm">
                        <a href="{% url 'pegs:popeg_delete' peg.pk %}">
                            <img src="{% static 'svg/delete.svg' %}">
                        </a>
                    </td>
                </tr>
            </a>
            {% endif %}
            {% endfor %}
        </tbody>
        {% endfor %}
    </table>
</content>

{% endblock %}

{% block script %}
<script>
    const update = pk => window.location.href = ``
</script>
{% endblock %}

pegs/templates/pegs/pegsystem_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

pegs/templates/pegs/pegsystem_create_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

pegs/templates/pegs/pegsystem_update_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

pegs/templates/pegs/popeg_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

pegs/templates/pegs/popeg_create_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

pegs/templates/pegs/popeg_update_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}