maps/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('accounts/registration/', views.RegisterView.as_view(), name="registration"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('streetmarkers.urls')),
    path('user/pegs/', include('pegs.urls')),
    path('admin/', admin.site.urls),
]

pegs/urls.py
from django.urls import path

from . import views

app_name = 'pegs'

urlpatterns = [
    path('', views.PegDetailView.as_view(), name='peg_detail'),
    path('create/pegsystem/', views.PegSystemCreate.as_view(), name='pegsystem_create'),
    path('update/pegsystem/<int:pk>', views.PegSystemUpdate.as_view(), name='pegsystem_update'),
    path('delete/pegsystem/<int:pk>', views.PegSystemDelete.as_view(), name='pegsystem_delete'),
    path('<int:pk>/create/popeg/', views.POPegCreate.as_view(), name='popeg_create'),
    path('update/popeg/<int:pk>', views.POPegUpdate.as_view(), name='popeg_update'),
    path('delete/popeg/<int:pk>', views.POPegDelete.as_view(), name='popeg_delete'),
]

streetmarkers/urls.py
from django.urls import path

from . import views

app_name = 'streetmarkers'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('user/palaces/', views.UserPalaceView.as_view(), name='user_palace'),
    path('user/palaces/create', views.PalaceCreate.as_view(), name='palace_create'),
    path('user/palaces/update/<int:pk>', views.PalaceUpdate.as_view(), name='palace_update'),
    path('user/palaces/delete/<int:pk>', views.PalaceDelete.as_view(), name='palace_delete'),
    path('user/<int:pk>/create/path', views.PathCreate.as_view(), name='path_create'),
    path('user/paths/update/<int:pk>', views.PathUpdate.as_view(), name='path_update'),
    path('user/paths/delete/<int:pk>', views.PathDelete.as_view(), name='path_delete'),
    path('user/markers/update/<int:pk>', views.BasicMarkerUpdate.as_view(), name='marker_update'),
    path('user/markers/delete/<int:pk>', views.BasicMarkerDelete.as_view(), name='marker_delete'),
    path('map/', views.MapPageView.as_view(), name='map'),
    path('ajax/create_palace/', views.create_palace, name='create_palace'),
    path('ajax/create_path/', views.create_path, name='create_path'),
    path('ajax/create_marker/', views.create_marker, name='create_marker'),
    path('ajax/load_markers/', views.load_markers, name='load_markers'),
    path('ajax/get_palaces/', views.get_palaces, name='get_palaces'),
    path('ajax/<int:pk>/get_paths/', views.get_paths, name='get_paths'),
    path('ajax/<int:pk>/get_markers/', views.get_markers, name='get_markers')
]

templates/base_generic.html
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .base-generic-container {
            position: relative;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
        }

        .base-generic-header {
            height: 50px;
        }

        .base-generic-footer {
            position: absolute;
            bottom: 0;
            height: 50px;
            width: 100%;
            margin-top: 10px;
            padding: 0;
        }
    </style>

    {% block style %}{% endblock style%}

</head>

<body>
    <div class="base-generic-container">
        <header class="base-generic-header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'streetmarkers:home' %}">MEMNUT</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'streetmarkers:user_palace' %}">Palaces</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'pegs:peg_detail' %}">Peg Systems</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'streetmarkers:map' %}">Map</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <footer class="base-generic-footer bg-light">
            <div class="container">
                <p class="text-center">MEMNUT MEMNUT MEMNUT</p>
            </div>
        </footer>
        <div class="m-5">
            {% block content %}{% endblock content %}
        </div>


        {% block script %}{% endblock script %}
    </div>
</body>

</html>