maps/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('accounts/registration/', views.RegisterView.as_view(), name="registration"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('streetmarkers.urls')),
    path('user/pegs/', include('pegs.urls')),
    path('admin/', admin.site.urls),
]

streetmarkers/urls.py
from django.urls import path

from . import views

app_name = 'streetmarkers'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('user/palaces/', views.UserPalaceView.as_view(), name='user_palace'),
    path('user/palaces/create', views.PalaceCreate.as_view(), name='palace_create'),
    path('user/palaces/update/<int:pk>', views.PalaceUpdate.as_view(), name='palace_update'),
    path('user/palaces/delete/<int:pk>', views.PalaceDelete.as_view(), name='palace_delete'),
    path('user/<int:pk>/create/path', views.PathCreate.as_view(), name='path_create'),
    path('user/paths/update/<int:pk>', views.PathUpdate.as_view(), name='path_update'),
    path('user/paths/delete/<int:pk>', views.PathDelete.as_view(), name='path_delete'),
    path('user/markers/update/<int:pk>', views.BasicMarkerUpdate.as_view(), name='marker_update'),
    path('user/markers/delete/<int:pk>', views.BasicMarkerDelete.as_view(), name='marker_delete'),
    path('map/', views.MapPageView.as_view(), name='map'),
    path('ajax/create_palace/', views.create_palace, name='create_palace'),
    path('ajax/create_path/', views.create_path, name='create_path'),
    path('ajax/create_marker/', views.create_marker, name='create_marker'),
    path('ajax/load_markers/', views.load_markers, name='load_markers'),
    path('ajax/get_palaces/', views.get_palaces, name='get_palaces'),
    path('ajax/<int:pk>/get_paths/', views.get_paths, name='get_paths'),
    path('ajax/<int:pk>/get_markers/', views.get_markers, name='get_markers')
]

streetmarkers/models.py
from django.db import models
from django.contrib.auth.models import User

class Palace(models.Model):
    title = models.CharField(max_length=30)
    createdBy = models.ForeignKey(User, on_delete=models.PROTECT)
    
    def get_user_path_set(self):
        return self.path_set.filter(createdBy=self.createdBy) 
    
    @property
    def path_count(self):
        return len(self.get_user_marker_set())
    
    def __str__(self):
        return self.title

class PathType(models.Model):
    typeName = models.CharField(max_length=30)
    def __str__(self):
        return self.typeName

class Path(models.Model):
    title = models.CharField(max_length=30)
    palace = models.ForeignKey(Palace, on_delete=models.PROTECT)
    type = models.ForeignKey(PathType, on_delete=models.PROTECT, null=True)
    createdBy = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def get_user_marker_set(self):
        return self.basemarker_set.filter(path=self)
    
    @property
    def marker_count(self):
        return len(self.get_user_marker_set())


    def __str__(self):
        return self.title

class MarkerType(models.Model):
    typeName = models.CharField(max_length=30)
    def __str__(self):
        return self.typeName

class BaseMarker(models.Model):
    title = models.CharField(max_length=300)
    lat = models.FloatField()
    lng = models.FloatField()
    path = models.ForeignKey(Path, on_delete=models.PROTECT, null=True)
    palace = models.ForeignKey(Palace, on_delete=models.PROTECT, null=True)
    createdBy = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    type = models.ForeignKey(MarkerType, on_delete=models.PROTECT, null=True)
    def __str__(self):
        return self.title

#Maker Type: 'basic'
class BasicMarker(BaseMarker):
    infoText = models.TextField()

class PalaceOwner(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    palace = models.ForeignKey(Palace, on_delete=models.CASCADE)

maps/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2'] 

maps/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.edit import FormView
from django.contrib import messages
from .forms import CreateUserForm
from django.urls import reverse_lazy

class RegisterView(FormView):
    template_name = "registration/registration.html"
    form_class = CreateUserForm 
    success_url = reverse_lazy('login') 
    def form_valid(self, form):
        user = form.cleaned_data.get('username')
        messages.success(self.request, 'Account was created for ' + user)
        form.save()
        return super().form_valid(form)

streetmarkers/views.py
import json
from django.conf import settings
from django.forms import modelform_factory, ModelForm
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .models import Palace, Path, BasicMarker, MarkerType, PathType

### logging ###
import logging
import logging.config
import sys

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    }
}

logging.config.dictConfig(LOGGING)
######

import markdown

class UserPalaceView(LoginRequiredMixin, ListView):
    model = Palace
    template_name = 'streetmarkers/user_palace.html'
    paginate_by = 5

    def get_queryset(self):
        return Palace.objects.filter(createdBy=self.request.user).order_by('title')


class UserPalaceDetailView(LoginRequiredMixin, DetailView):
    model = Palace

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paths'] = Path.objects.filter(
            createdBy=self.request.user).filter(palace=self.get_object())
        return context


class UserPathDetailView(LoginRequiredMixin, DetailView):
    model = Path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['markers'] = BasicMarker.objects.filter(
            createdBy=self.request.user).filter(path=self.get_object())
        return context


class HomePageView(TemplateView):
    template_name = 'streetmarkers/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# class PathForm(ModelForm):
#     class Meta:
#         model = Path
#         fields = ['title', 'palace']
#     def __init__(self, user, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['palace'].queryset = Palace.objects.filter(createdBy=user)

class MapPageView(LoginRequiredMixin, TemplateView):
    template_name = 'streetmarkers/map.html'

    # support multiple form (marker) types by adding form list to context
    # use bootstrap forms to render conditional on a select tag
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basicMarkerForm'] = modelform_factory(BasicMarker, fields=("title", "infoText"))
        #context['basicPathForm'] =  PathForm(user=self.request.user) 
        context['basicPathForm'] =  modelform_factory(Path, fields=("title",)) 
        context['basicPalaceForm'] = modelform_factory(Palace, fields=("title",)) 
        context['markers'] = [ {
            'title': m.title,
            'palace': m.palace,
            'path': m.path,
            'type': m.type,
            'lat': m.lat,
            'lng': m.lng,
            'infoText': markdown.markdown(m.infoText, safe_mode=True)
        } for m in BasicMarker.objects.filter(createdBy=self.request.user).all()]
        context['palaces'] = Palace.objects.filter(createdBy=self.request.user)
        return context

# create palace
@login_required
def create_palace(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        response_data = {}

        palace = Palace(
            createdBy=request.user, 
            title=title, 
        )
        palace.save()

        response_data['result'] = 'Create palace successful!'
        response_data['pk'] = palace.pk
        response_data['title'] = palace.title

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

# create path 
@login_required
def create_path(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        palace = Palace.objects.get(pk=request.POST.get('palace'))
        type = PathType.objects.get(typeName='basic')
        response_data = {}

        path = Path(
            createdBy=request.user, 
            title=title, 
            palace=palace, 
            type=type
        )
        path.save()

        response_data['result'] = 'Create path successful!'
        response_data['pk'] = path.pk
        response_data['title'] = path.title

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

#create marker
@login_required
def create_marker(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        infoText = request.POST.get('infoText')
        lat = request.POST.get('lat')
        lng = request.POST.get('lng')
        palace = Palace.objects.filter(
            createdBy=request.user).get(pk=request.POST.get('palace'))
        path = Path.objects.filter(
            createdBy=request.user).get(pk=request.POST.get('path'))

        type = MarkerType.objects.get(typeName='basic')
        response_data = {}

        marker = BasicMarker(
            createdBy=request.user, 
            title=title, 
            palace=palace, 
            path=path, 
            type=type, 
            infoText=infoText, 
            lat=lat, 
            lng=lng
        )
        marker.save()

        response_data['result'] = 'Create marker successful!'
        response_data['pk'] = marker.pk
        response_data['title'] = marker.title
        response_data['infoText'] = marker.infoText
        response_data['lng'] = marker.lng
        response_data['lat'] = marker.lat

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

# loads all markers created by the logged in user
@login_required
def load_markers(request):
    if request.method == 'GET':
        basicMarkers = BasicMarker.objects.filter(createdBy=request.user) 
        markers = [ {
            'infoText': markdown.markdown(m.infoText, safe_mode=True),
            'lat': m.basemarker_ptr.lat,
            'lng': m.basemarker_ptr.lng,
            'title': m.basemarker_ptr.title,
            'path': m.basemarker_ptr.path.title,
            'palace': m.basemarker_ptr.palace.title,
        } for m in basicMarkers ]
        response_data = json.dumps(markers)
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

@login_required
def get_palaces(request):
    if request.method == 'GET':
        palaces = Palace.objects.filter(createdBy=request.user) 
        palaces = [ {
            'title': m.title,
            'pk': m.pk,
        } for m in palaces]
        response_data = json.dumps(palaces)
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

@login_required
def get_paths(request, pk):
    if request.method == 'GET':
        palace = Palace.objects.get(createdBy=request.user, pk=pk)
        paths = [ {
            'title': m.title,
            'pk': m.pk,
        } for m in palace.path_set.all()]
        response_data = json.dumps(paths)
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )

@login_required
def get_markers(request, pk):
    if request.method == 'GET':
        path = Path.objects.get(createdBy=request.user, pk=pk)
        markers = [ {
            'title': m.title,
            'lat': m.lat,
            'lng': m.lng,
            'infoText': markdown.markdown(m.infoText, safe_mode=True),
            'pk': m.pk,
        } for m in [BasicMarker.objects.get(pk=bm.pk) 
            for bm in path.basemarker_set.all() 
            if BasicMarker.objects.filter(pk=bm.pk).exists()]]
        response_data = json.dumps(markers)
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_Type="application/json"
        )


#Create Views
# assert user is createdBy user

class PalaceCreate(LoginRequiredMixin, CreateView):
    model = Palace 
    fields = ['title']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('streetmarkers:user_palace')

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

class PathCreate(LoginRequiredMixin, CreateView):
    model = Path 
    fields = ['title', 'type']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('streetmarkers:user_palace')

    def form_valid(self, form):

streetmarkers/templates/streetmarkers/basicmarker_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

streetmarkers/templates/streetmarkers/basicmarker_update_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

streetmarkers/templates/streetmarkers/home.html
{% extends 'base_generic.html' %}

{% block content %}
<header class="jumbotron jumbotron-fluid">
    <div class="container-fluid text-center">
        <h1 class="display-3">Build and Share Memory Palaces</h1>
        <p class="lead pb-4">build interactive memory palaces in the real world</p>
        <p><a href="{% url 'streetmarkers:map' %}" class="btn btn-primary btn-lg" role="button">START</a></p>
    </div>
</header>

<section class="container-fluid text-center py-4 mt-4" id="contact">
    <h2 class="display-4 pb-4 my-4">Super cool memory palace picture!</h2>
    <p class="lead pb-3">I can feel the mnemonic power!</p>
</section>
{% endblock %}

streetmarkers/templates/streetmarkers/map.html
{% load static %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Maps</title>
    <style>
        html,
        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        #container {
            position: relative;
            z-index: 0;
            width: 100%;
            height: 100%;
        }

        #pano {
            position: absolute;
            top: 0;
            left: 0;
        }

        #map {
            z-index: 10;
        }

        .big-map {
            height: 100%;
            width: 100%;
        }

        .pip-map {
            height: 250px;
            width: 250px;
            margin: 10px;
        }

        #floating-modal {
            display: none;
            position: absolute;
            min-width: 250px;
            max-width: 90%;
            min-height: 250px;
            max-height: 70vh;
            overflow: scroll;
            top: 50%;
            left: 50%;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            border: 1px solid #999;
            text-align: center;
            font-family: 'Roboto', 'sans-serif';
            line-height: 30px;
            transform: translate(-50%, -50%);
        }

        .info-window {
            color: blue;
        }
    </style>
</head>

<body>
    <div id="floating-modal" style="display: none;">
        <div id="basic-marker-form" style="display: none;">
            <form id="modal-marker-form">
                {% csrf_token %}
                {% bootstrap_form basicMarkerForm %}
                <button type="submit">create</button>
                <button type="button" onclick="hideModal();">cancel</button>
            </form>
        </div>
        <div id="basic-path-form" style="display: none;">
            <form id="modal-path-form">
                {% csrf_token %}
                {% bootstrap_form basicPathForm %}
                <button type="submit">create</button>
                <button type="button" onclick="hideModal();">cancel</button>
            </form>
        </div>
        <div id="basic-palace-form" style="display: none;">
            <form id="modal-palace-form">
                {% csrf_token %}
                {% bootstrap_form basicPalaceForm %}
                <button type="submit">create</button>
                <button type="button" onclick="hideModal();">cancel</button>
            </form>
        </div>
        <div id="modal-form-results"></div>
    </div>
    <div id="container">
        <div id="map" class="big-map"></div>
        <div id="pano" class="big-map" style="display: none;"></div>
    </div>
    <div id="marker-container">
        {% for marker in markers %}
        <map-marker hidden data-lat="{{ marker.lat }}" data-lng="{{ marker.lng }}"
            data-infoText="{{ marker.infoText }}">{{marker.title}}</map-marker>
        {% endfor %}
    </div>
    <script src="{% static 'streetmarkers/jquery-ui.min.js' %}"></script>
    <script src="{% static 'streetmarkers/map.js' %}"></script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD9jTGYNpWqhcKSA3dI_atkepXqAIvfnck&callback=initMap&libraries=drawing"></script>
</body>

</html>

streetmarkers/templates/streetmarkers/palace_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

streetmarkers/templates/streetmarkers/palace_create_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

streetmarkers/templates/streetmarkers/palace_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<div id="palaces" class="list-group m-4">
    {% for path in paths %}
    <a class="list-group-item list-group-item-action text-info" href="{% url 'streetmarkers:user_path_detail' path.pk %}">
        {{ path.title }}
    </a>
    {% endfor %}

</div>
{% endblock %}

streetmarkers/templates/streetmarkers/palace_update_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

streetmarkers/templates/streetmarkers/path_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

streetmarkers/templates/streetmarkers/path_create_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

streetmarkers/templates/streetmarkers/path_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="list-group m-4">
  {% for marker in markers %}
  <div class="list-group-item text-info">
      {{ marker.title }}
  </div>
  {% endfor %}
</div>
{% endblock %}

streetmarkers/templates/streetmarkers/path_update_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

streetmarkers/templates/streetmarkers/user_palace.html
{% extends 'base_generic.html' %}

{% load static %}

{% block style %}
<style>
  ul,
  li {
    list-style: none;
  }
</style>
{% endblock %}

{% block content %}
<div id="palaces">
  <h3 class="m-4 ">
    {{ user.username|title }}'s Palaces
    <span class="btn btn-default btn-sm">
      <a href="{% url 'streetmarkers:palace_create' %}">
        <img src="{% static 'svg/create.svg' %}">
      </a>
    </span>
  </h3>
  {% if palace_list %}
  <div>
    {% for palace in palace_list %}
    <div class="list-group">
      <button class="list-group-item d-flex justify-content-between" type="button" data-toggle="collapse"
        data-target="#paths-{{ forloop.counter0 }}" aria-expanded="false" aria-controls="paths-{{ forloop.counter0 }}">
        <h5> 
          {{ palace.title }}
        </h5>
        <div>
          <span class="btn btn-default btn-sm">
            <a href="{% url 'streetmarkers:path_create' palace.pk %}">
              <img src="{% static 'svg/add.svg' %}">
            </a>
          </span>
          <span class="btn btn-default btn-sm">
            <a href="{% url 'streetmarkers:palace_update' palace.pk %}">
              <img src="{% static 'svg/update.svg' %}">
            </a>
          </span>
          <span class="btn btn-default btn-sm">
            <a href="{% url 'streetmarkers:palace_delete' palace.pk %}">
              <img src="{% static 'svg/delete.svg' %}">
            </a>
          </span>
      </button>
      <ul id="paths-{{ forloop.counter0 }}" class="m-0 p-0 collapse">
        {% for path in palace.get_user_path_set %}
        <div class="list-group">
          <button class="list-group-item d-flex justify-content-between" type="button" data-toggle="collapse"
            data-target="#markers-{{ forloop.counter0 }}" aria-expanded="false"
            aria-controls="markers-{{ forloop.counter0 }}">
            <h6 class="font-weight-bold">
              {{ path.title }}
            </h6>
            <div>
              <span class="btn btn-default btn-sm">
                <a href="{% url 'streetmarkers:path_update' path.pk %}">
                  <img src="{% static 'svg/update.svg' %}">
                </a>
              </span>
              <span class="btn btn-default btn-sm">
                <a href="{% url 'streetmarkers:path_delete' path.pk %}">
                  <img src="{% static 'svg/delete.svg' %}">
                </a>
              </span>
            </div>
          </button>
          <ul id="markers-{{ forloop.counter0 }}" class="m-0 p-0 collapse">
            {% for marker in path.get_user_marker_set %}
            <li class="list-group-item list-group-flush">
              <div class="d-flex justify-content-between">
                <div>
                  {{ marker.title }}
                </div>
                <div>
                  <span class="btn btn-default btn-sm">
                    <a href="{% url 'streetmarkers:marker_update' marker.pk %}">
                      <img src="{% static 'svg/update.svg' %}">
                    </a>
                  </span>
                  <span class="btn btn-default btn-sm">
                    <a href="{% url 'streetmarkers:marker_delete' marker.pk %}">
                      <img src="{% static 'svg/delete.svg' %}">
                    </a>
                  </span>
                </div>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <p>You don't have any palaces yet. Why don't you <a href="{% url 'streetmarkers:map' %}">create</a> one?</p>
  {% endif %}
</div>
{% endblock %}